---
- name: Install Nagios
  apt:
   update_cache: yes
   name: nagios3

- name: Update contacts config file
  copy:
   src: contacts_nagios2.cfg   
   dest: /etc/nagios3/conf.d/contacts_nagios2.cfg

- name: Upate service config file
  copy:
   src: services_nagios2.cfg
   dest: /etc/nagios3/conf.d/services_nagios2.cfg


